server:
  port: 8081

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/Knya3ev/cloud-config.git
          uri: D:/JAVA projects/Work/cloud-config
          search-paths: '{application}'
management:
  endpoint:
    web:
      exposure:
        include: refresh, bus-refresh, beans, env

