server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Knya3ev/cloud-config.git
          search-paths: config/{application}/


