server:
  port: 8081

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Knya3ev/cloud-config.git
          search-paths: config/app/, config/micro-service
management:
  endpoint:
    web:
      exposure:
        include: refresh, bus-refresh, beans, env

